### ISSUE TITLE
When I use rsync to deploy the image server, what the value of REMOTE_URL should I assign to?

### ISSUE THREAD

**Issue by bigbearishappy** [PocketNC/bbb-ostree-helper-scripts#3]
I tried to deploy a image server with rsync. And I can access to the server with rsync in client board. But when I want to continue the step to pull the image.The log showed it can't parse the url I provided.
I tried the following values:
export REMOTE_URL=192.168.113.27/ftp
export REMOTE_URL=rsync://192.168.113.27/ftp

None of them can make it work.
I would be appreciate if someone can help me out~

**Comment by jallwine** [comment]
As far as I know, ostree only supports http for retrieving files. You can use rsync to copy your files over to the server, but the server will need to be running an http server that serves static files from the ostree repository.

**Comment by bigbearishappy** [comment]
Thank you for your reply. I finally deploy the http server with nginx, and it works fine now.
