### ISSUE TITLE
Error happens when use the static-delta apply-offline

### ISSUE THREAD

**Issue by bigbearishappy** [PocketNC/bbb-ostree-helper-scripts#4]
I can generate the static delta successfully by following the step in readme.
But when I want to apply the static delta to my device. It shows the following error log:
`error: Cannot execute delta offline: contains nonempty http fallback entries`

The command I used to generate the static delta:
`ostree static-delta generate --from=bb.org/testing/2020-06-01/buster-iot --to=bb.org/testing/2021-08-09/buster-iot`
The command I used to apply the static delta:
`ostree static-delta apply-offline deltas/D9/JEeuIBHkCn_iGOrCnC_hUrsZZ+zeRFniEFgblCRH8-rQDGCSJ7O84cPuQ7_of+EFG34KEjezzVOzb42xmV42o/`

Is there anything I did incorrect or missing?
Looking forward to the reply~

**Comment by bigbearishappy** [comment]
I find out if I push both the images I want to the same ostree branch. And generate the static-delta file with the following parameter
`--min-fallback-size=0 --inline --filename=test.delta`

Now I can apply the test.delta file to my device and deploy it successfully
`ostree static-delta apply-offline test.delta`
`ostree admin deploy commit-ID`

I tried to generate the delta file from different ostree branch. But it failed when I apply it on device.
Is there any idea about this failure?

**Comment by jallwine** [comment]
I’m afraid I’m not very familiar with the different ways of interacting with static deltas. I get the impression that once you generate the static deltas and update your summary file, the client systems will automatically leverage those static deltas when pulling down a specific commit that would benefit from that static delta.

**Comment by bigbearishappy** [comment]
Thank you for your reply.As now I can use the static-delta properly. Maybe there is no need to find out reason of the branch issue.I will pay attention to this problem in my deployment.
